name: CI

on:
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: npm
      - name: yarn install, lint, test and build
        run: |
          yarn install --immutable
          yarn run lint
          yarn run test
          yarn run build
